ROTATING_DISTANCE = 14.0
ROTATING_DISTANCE_AV = 10.0
ROTATING_ANGLE_MIN = 6.5
ROTATING_CONST = 100.0
ROTATING_ANGULAR_SPEED = 2.0

ATACHING_DISTANCE_MIN = 5.0
ATACHING_DISTANCE_MAX = 5.5
ATACHING_ANGLE_MAX = 3.0
DISTANCE_BETWEEN_SRF_SENSORS = 23.5
LINEAR_MOVING_VELOCITY = 0.00001

VERIFICATION_ANGLE = 2.0
VERIFICATION_DISTANCE = 4.0

GRIPPER_OPEN_PRESSURE_CONST = 0.5
GRIPPER_CLOSE_PRESSURE_CONST = 0.8
GRIPPER_OPEN_POSITION = 1.0
GRIPPER_CLOSE_POSITION = 0.0

MAX_MOVING_VELOCITY = 0.3

POSITION_ERROR_MARGIN = 0.03

ERROR_COULDNT_ATTACH_TO_CART = (1, "Couldn't attach to cart")